/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rjj;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;

/**
 *
 * @author ibrah
 */
public class PasscodeChanger extends javax.swing.JFrame {

    /**
     * Creates new form PasscodeChanger
     */
    public PasscodeChanger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        New_Passcode_field = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Re_new_passcode_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Done1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.setText("Change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        New_Passcode_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                New_Passcode_fieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Re-Enter your new Passcode");

        Re_new_passcode_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Re_new_passcode_fieldKeyPressed(evt);
            }
        });

        jLabel2.setText("New Passcode");

        jLabel1.setText("Type the new passcode and relog for activation!");

        Done1.setText("취소");
        Done1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Done1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Re_new_passcode_field)
                            .addComponent(New_Passcode_field))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Done1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(New_Passcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Re_new_passcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Done1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        change_passcode_now();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Done1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Done1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Done1ActionPerformed

    private void Re_new_passcode_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Re_new_passcode_fieldKeyPressed
        // TODO add your handling code here:        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
             change_passcode_now();
        }
    }//GEN-LAST:event_Re_new_passcode_fieldKeyPressed

    private void New_Passcode_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_New_Passcode_fieldKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            change_passcode_now();
        }
    }//GEN-LAST:event_New_Passcode_fieldKeyPressed
//all gettext() down bellow is changed to get password. Deprecated. As of Java 2 platform v1.2, replaced by getPassword
    private void change_passcode_now()
    {
        if (String.valueOf(New_Passcode_field.getPassword()).equals(String.valueOf(Re_new_passcode_field.getPassword())))
        {
            if (String.valueOf(New_Passcode_field.getPassword()).equals("") || String.valueOf(Re_new_passcode_field.getPassword()).equals(""))
            {
                Error_Show_Frame Error_banner=new Error_Show_Frame();
                Error_banner.setVisible(true);
                Error_banner.setLocationRelativeTo(null);
                Error_Show_Frame.Error_Report.setText("Passcode Field is Empty");
            }else{
                try {
                    PrintWriter fout=new PrintWriter(new File(".\\Globalworkpath\\plainfile.txt"));
                    //fout.println(AES.encrypt(String.valueOf(New_Passcode_field.getPassword()), "NOC_just_in_case_1985"));
                    fout.println(AES.encrypt(String.valueOf(New_Passcode_field.getPassword()), "NOC_just_in_case_1985"));
                    fout.close();
                    System.exit(1);
                    
                } catch (FileNotFoundException ex) {
                    java.util.logging.Logger.getLogger(PasscodeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                
                        
            }
        }else
        {
           
            Error_Show_Frame Error_banner=new Error_Show_Frame();
            Error_banner.setVisible(true);
            Error_banner.setLocationRelativeTo(null);
            Error_Show_Frame.Error_Report.setText("Passcode Missmatch");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasscodeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasscodeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasscodeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasscodeChanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasscodeChanger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done1;
    private javax.swing.JPasswordField New_Passcode_field;
    private javax.swing.JPasswordField Re_new_passcode_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
