/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rjj;

import java.awt.Dimension;
import java.io.File;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.ImageIcon;
import rjj.main;
import static rjj.main.Client_1_name;
import static rjj.main.Client_2_name;
import static rjj.main.Client_3_name;
import static rjj.main.Client_4_name;
import static rjj.main.Global_work_path;

/**
 *
 * @author ibrah
 */
public class StartJ extends javax.swing.JFrame {

    /**
     * Creates new form StartJ
     */
    public StartJ() {
        initComponents();
        //File indestbeff = new File("C:\\Users\\ibrah\\Documents\\NetBeansProjects\\RelayJ\\Globalworkpath\\Clients_Names.txt");
//        File indestbeff_N = new File(".\\Globalworkpath\\Clients_Names.txt");
//        try ( Scanner finn = new Scanner(indestbeff_N)) {
//            while (finn.hasNext()) {
//              BN_1.setText(finn.nextLine());
//              BN_2.setText(finn.nextLine());
//              BN_3.setText(finn.nextLine());
//              BN_4.setText(finn.nextLine());
//            }
//            finn.close();
//        } catch (Exception e) {
//        }
        BN_1.setText(Client_1_name.getText());
        BN_2.setText(Client_2_name.getText());
        BN_3.setText(Client_3_name.getText());
        BN_4.setText(Client_4_name.getText());
        File indestbeff_IP = new File(".\\Globalworkpath\\IP_Addresses.txt");
        try ( Scanner finn = new Scanner(indestbeff_IP)) {
            while (finn.hasNext()) {
              BN_IP_1.setText(finn.nextLine());
              BN_IP_2.setText(finn.nextLine());
              BN_IP_3.setText(finn.nextLine());
              BN_IP_4.setText(finn.nextLine());
            }
            finn.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        BN_1 = new javax.swing.JTextField();
        BN_2 = new javax.swing.JTextField();
        BN_3 = new javax.swing.JTextField();
        BN_4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Done = new javax.swing.JButton();
        BN_IP_1 = new javax.swing.JTextField();
        BN_IP_2 = new javax.swing.JTextField();
        BN_IP_3 = new javax.swing.JTextField();
        BN_IP_4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Done1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel10.setText("송출제어장치");

        jLabel1.setText(" 고객 1");

        jLabel2.setText(" 고객 2");

        jLabel3.setText(" 고객 3");

        jLabel4.setText(" 고객 4");

        Done.setText(" 다음");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        jLabel5.setText("IP 1");

        jLabel6.setText("IP 2");

        jLabel7.setText("IP 3");

        jLabel8.setText("IP 4");

        Done1.setText("취소");
        Done1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Done1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(BN_3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(BN_2)
                        .addComponent(BN_4))
                    .addComponent(jLabel2)
                    .addComponent(BN_1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BN_IP_1)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Done1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BN_IP_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(BN_IP_3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BN_IP_4, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BN_IP_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BN_1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BN_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BN_IP_2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BN_3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BN_IP_3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BN_4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BN_IP_4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Done)
                    .addComponent(Done1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        // TODO add your handling code here:
        try {
            //PrintWriter fout=new PrintWriter(new File("C:\\Users\\ibrah\\Documents\\NetBeansProjects\\RelayJ\\Globalworkpath\\Clients_Names.txt"));
            //PrintWriter fout=new PrintWriter(new File(".\\Globalworkpath\\Clients_Names.txt"));
            PrintWriter fout=new PrintWriter(new File(".\\Globalworkpath\\Clients_Names.txt"),"UTF-8");
            fout.println(BN_1.getText());
            fout.println(BN_2.getText());
            fout.println(BN_3.getText());
            fout.println(BN_4.getText());
            fout.close();
        } catch (Exception e) {
            System.out.print(e);
        }  
        try {
            //PrintWriter fout=new PrintWriter(new File("C:\\Users\\ibrah\\Documents\\NetBeansProjects\\RelayJ\\Globalworkpath\\Clients_Names.txt"));
            PrintWriter fout=new PrintWriter(new File(".\\Globalworkpath\\IP_Addresses.txt"));
            fout.println(BN_IP_1.getText());
            fout.println(BN_IP_2.getText());
            fout.println(BN_IP_3.getText());
            fout.println(BN_IP_4.getText());
            fout.close();
        } catch (Exception e) {
            System.out.print(e);
        }  
//        main frame = new main();
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
//        frame.setSize(1150, 1000);
//        frame.setMinimumSize(new Dimension(1650, 1045));
//        frame.setMaximumSize(new Dimension(1650, 1045));
        //frame.setIconImage(new ImageIcon("/relayj/IconImages/RBPI_noclick.png").getImage());
//        frame.setIconImage(new ImageIcon("./IconImages/RBPI_noclick.png").getImage());
        System.exit(1);
        //this.setVisible(false);
    }//GEN-LAST:event_DoneActionPerformed

    private void Done1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Done1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_Done1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartJ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartJ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BN_1;
    private javax.swing.JTextField BN_2;
    private javax.swing.JTextField BN_3;
    private javax.swing.JTextField BN_4;
    private javax.swing.JTextField BN_IP_1;
    private javax.swing.JTextField BN_IP_2;
    private javax.swing.JTextField BN_IP_3;
    private javax.swing.JTextField BN_IP_4;
    private javax.swing.JButton Done;
    private javax.swing.JButton Done1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
